// Role-based UI Customisation and Permission Management
// made possible by user roles and their capabilities.
// The white list defines what features user can see and access.
// The role of the user is stored in JWT token the user possess.
//
// Introduced in v14.
//
module.exports = {
  'public': [
    'geometry-read',
    'account-login-form',
    'account-password-reset-request',
  ],
  'invited': [
    'account-signup',
  ],
  'resetter': [
    'account-password-reset',
  ],
  // 'banned': [], // same as frozen?
  'frozen': [
    // not able to login
  ],
  'reader': [ // able to see content after login but not modify
    'account-auth',
    'account-update',
    'attachments-read',
    'comments-read',
    'geometry-read',
    'locations-read',
    'locations-search',
    'locations-filter',
    'locations-export-one',
    'locations-geometry',
    'locations-places',
    'locations-statustype',
    'locations-thumbnail',
    'map-geolocation',
    'posts-read',
    'users-read',
  ],
  // 'commenter': [], // same as reader but could comment?
  'writer': [
    'account-auth',
    'account-update',
    'attachments-read',
    'attachments-create',
    'attachments-update-own',
    'attachments-delete-own',
    'comments-read',
    'comments-create',
    'comments-update-own',
    'comments-delete-own',
    'geometry-read',
    'locations-read',
    'locations-search',
    'locations-filter',
    'locations-create',
    'locations-delete-own',
    'locations-events',
    'locations-export-one',
    'locations-geometry',
    'locations-import',
    'locations-places',
    'locations-statustype',
    'locations-thumbnail',
    'locations-update-any',
    'map-geolocation',
    'posts-read',
    'posts-create',
    'posts-update-own',
    'posts-delete-own',
    'posts-move-own',
    'statistics-read',
    'users-read',
  ],
  'moderator': [
    'account-auth',
    'account-update',
    'admin-users-read',
    'admin-users-rerole',
    'attachments-read',
    'attachments-create',
    'attachments-update-any',
    'attachments-delete-any',
    'comments-read',
    'comments-create',
    'comments-update-own',
    'comments-delete-any',
    'geometry-read',
    'locations-read',
    'locations-search',
    'locations-filter',
    'locations-create',
    'locations-delete-any',
    'locations-events',
    'locations-export-all',
    'locations-export-one',
    'locations-geometry',
    'locations-import',
    'locations-places',
    'locations-statustype',
    'locations-thumbnail',
    'locations-update-any',
    'map-geolocation',
    'posts-read',
    'posts-create',
    'posts-update-own',
    'posts-delete-any',
    'posts-move-any',
    'statistics-read',
    'users-read',
  ],
  'admin': [
    'account-auth', // allow login and any authentication with username
    'account-update',
    'admin-users-read',
    'admin-users-invite',
    'admin-users-rerole',
    'admin-users-delete',
    'attachments-read',
    'attachments-create',
    'attachments-update-any',
    'attachments-update-own',
    'attachments-delete-any',
    'attachments-delete-own',
    'comments-read',
    'comments-create',
    'comments-update-any',
    'comments-update-own',
    'comments-delete-any',
    'comments-delete-own',
    'geometry-read',
    'locations-read',
    'locations-search',
    'locations-filter',
    'locations-create',
    'locations-delete-any',
    'locations-delete-own',
    'locations-events',
    'locations-export-all',
    'locations-export-one',
    'locations-geometry',
    'locations-import',
    'locations-places',
    'locations-statustype',
    'locations-thumbnail',
    'locations-update-any',
    'locations-update-own',
    'map-geolocation',
    'posts-read',
    'posts-create',
    'posts-update-any',
    'posts-update-own',
    'posts-delete-any',
    'posts-delete-own',
    'posts-move-any',
    'posts-move-own',
    'statistics-read',
    'users-read',
  ],
  // 'dev': [], // for testing and beta features?
};
